<h4> Задание 1 </h4>

В с не будет присвоено ничего из-за несовпадения типов. 
```python
>>> a = 1
>>> b = "2"
>>> c = a + b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Получить 12:
```python
>>> c = str(a) + b
>>> print(c)
12
```

Получить 3:
```python
>>> c = a + int(b)
>>> print(c)
3
```
<hr>
<h4> Задание 2 </h4>

Код 

```python
import os

bash_command = ["cd ~/netology/sysadm-homeworks", "git status"]
result_os = os.popen(' && '.join(bash_command)).read()
for result in result_os.split('\n'):
    if result.find('modified') != -1:
        prepare_result = result.replace('\tmodified:   ', '')
        print(os.path.abspath(os.path.expandvars(prepare_result)))
```

Результат:

```python
vagrant@vagrant:~$ ./test1.py
/home/vagrant/01-intro-01/README.md
/home/vagrant/01-intro-01/netology.md
/home/vagrant/01-intro-01/new_dir/trial.md
```

<hr>
<h4> Задание 3 </h4>

```python
#!/usr/bin/env python3

import os
local = True
repo_path = os.path.expanduser('~/netology/sysadm-homeworks')

query = input('Do you wish to check local repo? y/n \n')
if query == 'n' or query == 'no':
    local = False
    repo_path = input('Please provide path to repo you want to check\n')
elif query != 'y' and query != 'yes':
    print('Not a valid input')
    exit()

if not os.access(repo_path, os.F_OK):
    print("Directory is restricted or doesn't exist")
    exit()

bash_command = ['cd ' + repo_path, 'git status']
result_os = os.popen(' && '.join(bash_command)).read()
for result in result_os.split('\n'):
    if result.find('modified') != -1:
        prepare_result = result.replace('\tmodified:   ', '')
        if local:
            print(os.path.abspath(os.path.expandvars(prepare_result)))
        else:
            print(repo_path + '/' + prepare_result)
```
Результат: 

Локальная:
```bash
vagrant@vagrant:~$ ./task423.py
Do you wish to check local repo? y/n 
y
/home/vagrant/01-intro-01/README.md
/home/vagrant/01-intro-01/netology.md
/home/vagrant/01-intro-01/new_dir/trial.md
vagrant@vagrant:~$ 
```
Не локальная, существующая, но не валидная:
```bash
vagrant@vagrant:~$ ./task423.py
Do you wish to check local repo? y/n 
n
Please provide path to repo you want to check
/home/carrie
fatal: not a git repository (or any of the parent directories): .git
```
Не локальная и не существующая:
```bash
vagrant@vagrant:~$ ./task423.py
Do you wish to check local repo? y/n 
n
Please provide path to repo you want to check
/home/jav
Directory is restricted or doesn't exist

```
Не локальная, существующая, валидная:
```bash
vagrant@vagrant:~$ ./task423.py
Do you wish to check local repo? y/n 
n
Please provide path to repo you want to check
/home/carrie/devops-netology
/home/carrie/devops-netology/branching/example.txt
/home/carrie/devops-netology/branching/testdir/example2.md
```

<hr>
<h4> Задание 4 </h4>

```python
#!/usr/bin/env python3

import socket
import time

service_list = ['drive.google.com', 'mail.google.com', 'google.com']
last_check_result = {}
first_start = True


def get_ip(service):
    current_ip = socket.gethostbyname(service)
    print(service, '-', current_ip)
    if not first_start:
        check_ip(service, current_ip)
    last_check_result[service] = current_ip


def check_ip(service, ip):
    old_ip = last_check_result[service]
    if ip != old_ip:
        print('[ERROR] ' + service + ' IP mismatch: ' + old_ip + ' ' + ip)


while 1 == 1:
    for i in service_list:
        get_ip(i)
    first_start = False
    print()
    time.sleep(60)

```
Результат:
```bash
vagrant@vagrant:~$ ./test.py
drive.google.com - 173.194.222.194
mail.google.com - 142.251.1.83
google.com - 142.250.150.139

drive.google.com - 173.194.222.194
mail.google.com - 142.251.1.17
[ERROR] mail.google.com IP mismatch: 142.251.1.83 142.251.1.17
google.com - 142.250.150.139
```